### ISSUE TITLE
Implement async_run as described in #4630

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb-ruby#24]
Ruby driver PR https://github.com/rethinkdb/rethinkdb/pull/5973

In reference to https://github.com/rethinkdb/rethinkdb/issues/4630

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tinco** [comment]
Hi @srh if I remember correctly this feature was already implemented in 2020 in this commit:

https://github.com/rethinkdb/rethinkdb-ruby/commit/02571eec6a7d99b673392e0e33f52b097a50b945

Sorry I didn't report that back in the original report.
